runtime: python27
threadsafe: true
api_version: 1

# libraries:
# - name: flask
#   version: "0.12"

# [START handlers]
handlers:
- url: /app/static
  static_dir: static
- url: .*
  script: manage.app
# [END handlers]